name: CustomMobsQuests
version: 2.0
description: Quests module for CustomMobs
author: PikaMug
website: https://github.com/PikaMug/CustomMobsQuestsModule

main: me.pikamug.custommobsquests
depend: [CustomMobs, Quests]
