name: CustomMobsQuests
version: 2.1
description: Quests module for CustomMobs
author: Browsit
website: https://github.com/Browsit/CustomMobsQuestsModule

main: org.browsit.custommobsquests.CustomMobsModule
depend: [CustomMobs, Quests]
